# .github/actions/yarn-build/action.yml
name: Yarn Build
description: "Checkout, install dependencies, lint, and build the project"
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "16.x"

    - name: Install dependencies
      run: yarn install --frozen-lockfile
      shell: bash

    - name: Lint code
      run: yarn lint
      shell: bash

    - name: Build project
      run: yarn build
      shell: bash