# .github/workflows/deploy.yml
name: Deploy

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy-prod:
    if: github.ref == 'refs/heads/main'
    environment: main
    runs-on: ubuntu-latest
    steps:
      - name: Run Yarn Build
        uses: ./.github/actions/yarn-build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: S3 Deploy
        run: |
          aws s3 sync --delete ./build s3://${{ secrets.S3_BUCKET }} --region ${{ secrets.AWS_REGION }}

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.DISTRIBUTION_ID }} \
            --paths "/*"

  deploy-stg:
    if: github.ref == 'refs/heads/develop'
    environment: develop
    runs-on: ubuntu-latest
    steps:
      - name: Run Yarn Build
        uses: ./.github/actions/yarn-build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: S3 Deploy
        run: |
          aws s3 sync --delete ./build s3://${{ secrets.S3_BUCKET }} --region ${{ secrets.AWS_REGION }}

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.DISTRIBUTION_ID }} \
            --paths "/*"